---
title: "Week3_Assignment"
author: "Kam Mix"
date: "September 21, 2015"
output: html_document
---
### Base R Version

#### Data
Let us begin by simulating our sample data of 3 factor variables and 4 numeric variables.

```{r echo = T}
## Simulate some data

## 3 Factor Variables
FacVar1=as.factor(rep(c("level1","level2"),25))
FacVar2=as.factor(rep(c("levelA","levelB","levelC"),17)[-51])
FacVar3=as.factor(rep(c("levelI","levelII","levelIII","levelIV"),13)[-c(51:52)])

## 4 Numeric Vars
set.seed(123)
NumVar1=round(rnorm(n=50,mean=1000,sd=50),digits=2) ## Normal distribution
set.seed(123)
NumVar2=round(runif(n=50,min=500,max=1500),digits=2) ## Uniform distribution
set.seed(123)
NumVar3=round(rexp(n=50,rate=.001)) ## Exponential distribution
NumVar4=2001:2050

simData=data.frame(FacVar1,FacVar2,FacVar3,NumVar1,NumVar2,NumVar3,NumVar4)
```

#### One Variable: Numeric Variable

```{r echo = T, results="asis", warning=FALSE,message=FALSE}
plot(simData$NumVar1,type="o") ## Index plot
hist(simData$NumVar1) ## histogram
plot(density(simData$NumVar1)) ## Kernel density plot
boxplot(simData$NumVar1) ## box plot





